export type User = {
	id: string;
	fullName: string;
	lastName: string;
	email: string;
    phoneNumber: string;
    status?: string;
    createdDate: string | Date;
    role: string;
	state: string;
};

export const fakeData: User[] = [
	{
		id: '9s41rp',
		fullName: 'Kelvin Langosh',
		lastName: 'Langosh',
		email: 'Jerod14@hotmail.com',
		state: 'Ohio',
		role: 'Store Manager',
		phoneNumber: '+234789982185',
		createdDate: '26-06-2022',
		status: 'Active',
	},
	{
		id: '08m6rx',
		fullName: 'Molly Purdy',
		lastName: 'Purdy',
		email: 'Hugh.Dach79@hotmail.com',
		state: 'Rhode Island',
		role: 'Store Manager',
		phoneNumber: '+234789982185',
		createdDate: '26-06-2022',
		status: 'Active',
	},
	{
		id: '5ymtrc',
		fullName: 'Henry Lynch',
		lastName: 'Lynch',
		email: 'Camden.Macejkovic@yahoo.com',
		state: 'California',
		role: 'Store Manager',
		phoneNumber: '+234789982185',
		createdDate: '26-06-2022',
		status: 'Active',
	},
	{
		id: 'ek5b97',
		fullName: 'Glenda Douglas',
		lastName: 'Douglas',
		email: 'Eric0@yahoo.com',
		state: 'Montana',
		role: 'Store Manager',
		phoneNumber: '+234789982185',
		status: 'Active',
		createdDate: '26-06-2022',
	},
	{
		id: 'xxtydd',
		fullName: 'Leone Williamson',
		lastName: 'Williamson',
		email: 'Ericka_Mueller52@yahoo.com',
		state: 'Colorado',
		role: 'Store Manager',
		phoneNumber: '+234789982185',
		createdDate: '26-06-2022',
	},
	{
		id: 'wzxj9m',
		fullName: 'Mckenna Friesen',
		lastName: 'Friesen',
		email: 'Veda_Feeney@yahoo.com',
		state: 'New York',
		role: 'Store Manager',
		phoneNumber: '+234789982185',
		createdDate: '26-06-2022',
	},
];

//50 us states array
export const usStates = [
	'Alabama',
	'Alaska',
	'Arizona',
	'Arkansas',
	'California',
	'Colorado',
	'Connecticut',
	'Delaware',
	'Florida',
	'Georgia',
	'Hawaii',
	'Idaho',
	'Illinois',
	'Indiana',
	'Iowa',
	'Kansas',
	'Kentucky',
	'Louisiana',
	'Maine',
	'Maryland',
	'Massachusetts',
	'Michigan',
	'Minnesota',
	'Mississippi',
	'Missouri',
	'Montana',
	'Nebraska',
	'Nevada',
	'New Hampshire',
	'New Jersey',
	'New Mexico',
	'New York',
	'North Carolina',
	'North Dakota',
	'Ohio',
	'Oklahoma',
	'Oregon',
	'Pennsylvania',
	'Rhode Island',
	'South Carolina',
	'South Dakota',
	'Tennessee',
	'Texas',
	'Utah',
	'Vermont',
	'Virginia',
	'Washington',
	'West Virginia',
	'Wisconsin',
	'Wyoming',
	'Puerto Rico',
];
